### ISSUE TITLE
Unable to log in through app

### ISSUE THREAD

**Issue by kaibagley** [metabrainz/listenbrainz-android#358]
Phone: Google Pixel 7 Pro
OS: GrapheneOS/AOSP 14
App: 2.4.2

When logging in, I am taken to the ListenBrainz login page within the app. After logging in, I see the ListenBrainz Listens page with a TypeError: Cannot read properties of undefined (reading 'APIBaseURI')

![Screenshot_20240208-155944](https://github.com/metabrainz/listenbrainz-android/assets/53884957/4475d637-146c-4702-bcd4-9441998e5861)

Nothing happens after this, going back to the app takes me back to the Profile/Login screen.

Thanks!

**Comment by arjanboltjes** [comment]
Identical issue here, just now. Fresh install of the app.
Phone: Fairphone 4
OS: /e/ OS version 1.17-s-20231109350748-stable-FP4

**Comment by StevenSteel7** [comment]
Phone: Galaxy S22
OS: One Ui 6
App: 2.4.2

same issue here..

**Comment by 07jasjeet** [comment]
Hello @kaibagley,  @arjanboltjes and @StevenSteel7, the ListenBrainz Server was down when you faced the issue, you will be able to log back in now.

**Comment by 07jasjeet** [comment]
Apologies for the inconvenience. Because we were unable to convey this message through the app's UI, we have fixed and added some warning. Thanks for reporting!

**Comment by kaibagley** [comment]
Hey @07jasjeet, unfortunately I'm still unable to log in, with the same behaviour as before.

**Comment by 07jasjeet** [comment]
@kaibagely Can you try out version 2.5.4 (Beta)? If you get our app from F-droid, We will be making a release shortly but looks like your app version is way behind our latest version. Although this shouldn't happen, try re-installing the app. Thanks for reporting!

**Comment by kaibagley** [comment]
I was using version 2.4.2 which I believe was the latest version a few days ago. I still don't have access to the newest version but I will wait until it appears on the releases page or Fdroid and get back to yoy

**Comment by kaibagley** [comment]
After downloading version 2.5.5 from github, when logging in I just see my normal Listens page, rather than the error that appeared before. However, this doesn't sign me into the app, whether I close the app, or go back or whatever. I'm signed into the WebView/browser window screen "within" the app, but not the app itself.

**Comment by Saijin-Naib** [comment]
Confirming behavior with 2.5.5 F-Droid.

**Comment by kaibagley** [comment]
Problem is solved with version 2.6.0 for me. Will leave this open for a little bit longer to make sure others are also seeing this as resolved

**Comment by arjanboltjes** [comment]
Coming back to this issue - see my earlier post above - I see that v. 2.6.1 now works for me.
Phone: Fairphone 4
OS: /e/ OS version 1.21.1-s-20240325389527-stable-FP4
